---
- name: Install Java and net-tools
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages (Java 11 + net-tools)
      apt:
        name:
          - openjdk-11-jre-headless
          - net-tools
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_check
      changed_when: false
      ignore_errors: true

    - name: Display Java version
      debug:
        msg: "{{ java_check.stderr_lines[0] | default('Java not installed or version check failed') }}"

- name: Download and unpack nexus installer
  hosts: webserver
  tasks: 
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result

    - name: Download Nexus tarball
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.85.0-03-linux-x86_64.tar.gz
        dest: /opt/
      register: download_nexus

    - name: Unpack nexus tarball
      unarchive:
        src: "{{download_nexus.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists  

    - name: Find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result

    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus folders
  hosts: webserver
  tasks:
    - name: Ensure group 'nexus' exists
      group:
        name: nexus
        state: present
    - name: Create user 'nexus'
      user:
        name: nexus
        group: nexus
    - name: Change ownership of nexus folders
      file:
        path: /opt/nexus
        state: directory
        recurse: yes
        owner: nexus
        group: nexus  
    - name: Change ownership of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        recurse: yes
        owner: nexus
        group: nexus       

- name: Start nexus with nexus user
  hosts: webserver
  become: True
  become_user: nexus     
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      ansible.builtin.command: /opt/nexus/bin/nexus start





- name: Verify nexus running
  hosts: webserver
  tasks:
    - name: Check with ps
      ansible.builtin.shell: ps aux | grep nexus
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      ansible.builtin.pause:
        minutes: 1
    - name: Check with netstat
      ansible.builtin.shell: netstat -plnt
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
   